### ISSUE TITLE
Audit logging ignores multitenant mode

### ISSUE THREAD

**Issue by martinvlk** [robertoschwald/grails-audit-logging-plugin#152]
Hi, we are implementing an application which uses the GORM multitenancy in DATABASE mode, e.g.
```
grails:
  gorm:
    multiTenancy:
      mode: DATABASE
```

However, the audit-logging plugin ignores the resolved tenant data source and always writes to the DEFAULT data source.

Could you add support for multitenancy?
